### PR TITLE
fix: Exclude example flags provided by node

### LINKED ISSUE #65: Result includes `--flag`, which is not a valid flag
Before you open this issue, please complete the following tasks:

* [x] use the search bar at the top of the page to search this repository for similar issues or discussions that have already been opened.
* [ ] if you are looking for help from the gulp team or community, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [ ] if you think there is a problem with the plugin you're using, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [x] if you think there is a bug in our code, open this issue.

### What were you expecting to happen?

`--flag` is not a valid flag, and thus it should not be reported.

`node --v8-options` includes `--flag` as an example:

```
The following syntax for options is accepted (both '-' and '--' are ok):
  --flag        (bool flags only)
  --no-flag     (bool flags only)
  --flag=value  (non-bool flags only, no spaces around '=')
  --flag value  (non-bool flags only)
  --            (captures all remaining args in JavaScript)

Options:
  --experimental (Indicates that V8 is running with experimental features enabled. This flag is typically not set explicitly but instead enabled as an implication of other flags which enable experimental features.)
        type: bool  default: --no-experimental
  --abort-on-contradictory-flags (Disallow flags or implications overriding each other.)
        type: bool  default: --no-abort-on-contradictory-flags
  --exit-on-contradictory-flags (Exit with return code 0 on contradictory flags.)
        type: bool  default: --no-exit-on-contradictory-flags
  --allow-overwriting-for-next-flag (temporary disable flag contradiction to allow overwriting just the next flag)
        type: bool  default: --no-allow-overwriting-for-next-flag
  ...
```

It looks like there is some logic to skip it, but it's not working: https://github.com/gulpjs/v8flags/blob/1f70fd1ce962dbf426a5fd17c7637248fc71c200/index.js#L95

### What actually happened?

`--flag` is included

### Please give us a sample of your gulpfile

```js
var v8flags = require("v8flags");
var fs = require("fs");
fs.rmSync(v8flags.configPath, { recursive: true });

v8flags((err, res) => {
  console.assert(!res.includes("--flag"));
});
```

### Terminal output / screenshots

```sh
$ node demo1.js
Assertion failed
```

### Please provide the following information:
* OS & version [e.g. MacOS Catalina 10.15.4]: MacOS
* node version (run `node -v`): v20.5.1
* npm version (run `npm -v`):
* gulp version (run `gulp -v`):

### Additional information

I am trying to upgrade to v4.0.0 in Babel: babel/babel#15908

### PR DESCRIPTION
**Pull request by sttk**
This PR is to fix the issue #65.

In recent Node.js, the output of `node --v8-options` contains extra lines in the `--xxx` format, like:
```
% node --v8-options
SSE3=1 SSSE3=1 SSE4_1=1 SSE4_2=1 SAHF=1 AVX=1 AVX2=1 FMA3=1 BMI1=1 BMI2=1 LZCNT=1 POPCNT=1 ATOM=0
The following syntax for options is accepted (both '-' and '--' are ok):
  --flag        (bool flags only)
  --no-flag     (bool flags only)
  --flag=value  (non-bool flags only, no spaces around '=')
  --flag value  (non-bool flags only)
  --            (captures all remaining args in JavaScript)

Options:
  --abort-on-contradictory-flags (Disallow flags or implications overriding each other.)
        type: bool  default: --noabort-on-contradictory-flags
  ...
```

Regarding this issue, we had implemented a solution to extract options from `Options:` onward, but there was a mistake in that. This PR is to correct that mistake. 

Closes #65

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -91,8 +91,8 @@ function getFlags(cb) {
 
     var index = result.indexOf('\nOptions:');
     if (index >= 0) {
+      result = result.slice(index);
       var regexp = /^\s\s--[\w-]+/gm;
```
Comment (nicolo-ribaudo) [inline index.js:95]: Does adding the `y` flag work?

```
var regexp = /^\s\s--[\w-]+/gmy;
regexp.lastIndex = index;
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/sticky#description

Comment (sttk) [reply index.js:95]: MDN says that `String#match` returns an array of all exec() results for `g` or `gy` flag, but actually does not return expected results.
```
let str = '  --xxx   --yyy   --zzz';
let regexp = /^\s\s--[\w-]+/g;                                                  
console.log(`str.match(${regexp}) = ${str.match(regexp)}`);
regexp = /^\s\s--[\w-]+/gy;
console.log(`str.match(${regexp}) = ${str.match(regexp)} (regexp.lastIndex = ${regexp.lastIndex})`);
regexp.lastIndex = 7;
console.log(`str.match(${regexp}) = ${str.match(regexp)} (regexp.lastIndex = ${regexp.lastIndex})`);

str = '  --xxx\n  --yyy\n  --zzz\n';
regexp = /^\s\s--[\w-]+/gm;
console.log(`str.match(${regexp}) = ${str.match(regexp)}`);
regexp = /^\s\s--[\w-]+/gmy;
console.log(`str.match(${regexp}) = ${str.match(regexp)} (regexp.lastIndex = ${regexp.lastIndex})`);
regexp.lastIndex = 7;
console.log(`str.match(${regexp}) = ${str.match(regexp)} (regexp.lastIndex = ${regexp.lastIndex})`);
--
% node regexp_stick_test.js
str.match(/^\s\s--[\w-]+/g) =   --xxx
str.match(/^\s\s--[\w-]+/gy) =   --xxx (regexp.lastIndex = 0)
str.match(/^\s\s--[\w-]+/gy) =   --xxx (regexp.lastIndex = 0)
str.match(/^\s\s--[\w-]+/gm) =   --xxx,  --yyy,  --zzz
str.match(/^\s\s--[\w-]+/gmy) =   --xxx (regexp.lastIndex = 0)
str.match(/^\s\s--[\w-]+/gmy) =   --xxx (regexp.lastIndex = 0)
%
```

In addition, `y` flag cause an eslint error because it is supported in Node.js `6.0.0` and later but this package (and other gulp packages) uses [eslint-config-gulp](https://github.com/gulpjs/eslint-config-gulp) which still supports syntax of Node.js `>= 0.10`.

Comment (nicolo-ribaudo) [reply index.js:95]: Although this package supports Node.js 10+, not 0.10+ 😅  It even uses features introduced in Node.js 10, such as `process.allowedNodeEnvironmentFlags`.

https://github.com/gulpjs/v8flags/blob/1f70fd1ce962dbf426a5fd17c7637248fc71c200/package.json#L16

Comment (phated) [reply index.js:95]: Our lint rules are in place to avoid certain community members from wasting our time as we work to release gulp 5. Once it is released, all linting and projects will be updated to support node 20+

**Comment by phated** [comment]
This needs a test. I'll look into adding it.

**Review by phated — APPROVED** [review]
