### PR TITLE
Change home directory lookup behaviour

### LINKED ISSUE #41: TypeError: Path must be a string. Received null
After upgrading ts-node from version 3.2 to 3.3, we started having this issue on our dev server. We can't reproduce it on our mac workstations.

It seams like this is introduced by the upgrade to v8flags@3.0.0.

We are downgrading as it fixes our issue but I wanted to let you know...

```
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at linux (/opt/apps/pbv4/release/08022017145510/node_modules/v8flags/config-path.js:19:25)
    at module.exports (/opt/apps/pbv4/release/08022017145510/node_modules/v8flags/config-path.js:32:10)
    at Object.<anonymous> (/opt/apps/pbv4/release/08022017145510/node_modules/v8flags/index.js:10:47)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
error Command failed with exit code 1.
```

### PR DESCRIPTION
**Pull request by Siilwyn**
Change the module that retrieves the user home directory. When on
Windows the module can still return null, moving fallback logic to the
config-path prevents it from returning null.

Switching to `homedir-pollyfil` resolves #41 since it's about Linux. However this switch causes one test to fail because it expects the home directory not to be found but with this switch the module does find the home directory. I can't get it to return null as it would need a Windows environment, changing `process.platform` leads to other problems, so the only way to test it is by stubbing the module I think. Would it be okay to bring in `sinon` for testing?

### CODE REVIEW

File: test.js [hunk 1]
```diff
@@ -70,7 +70,7 @@ describe('v8flags', function () {
     });
   });
 
-  it('should fall back to writing to a temp dir if user home can\'t be found', function (done) {
+  it.skip('should fall back to writing to a temp dir if user home can\'t be found', function (done) {
```
Comment (Siilwyn) [inline test.js]: This test fails because user home can be found.

File: index.js [hunk 2]
```diff
@@ -29,11 +29,6 @@ function fail (err) {
 }
 
 function openConfig (cb) {
-  var userHome = require('user-home');
```
Comment (Siilwyn) [inline index.js]: Moved this logic because `user-home` was being called by `config-path` so even if the module returns `null` it wouldn't get to this test.

**Comment by phated** [comment]
Can this be handled by enabling AppVeyor?  It looks like I didn't get it set up properly when we moved/renamed the project

**Comment by Siilwyn** [comment]
Maybe but I can't test it since I'm on Linux. :s

**Comment by phated** [comment]
@Siilwyn I've enabled it at https://ci.appveyor.com/project/phated/js-v8flags but you'll need to push a Windows-specific test (check out https://github.com/gulpjs/vinyl-fs if you need a pattern for this).

**Comment by Siilwyn** [comment]
Went with mocking because it's a lot faster for me to test locally than waiting for the CI to finish, thanks for support though!

While debugging the test I found out some other existing tests relied on each other to clear certain modules from the cache. This caused unpredictable test behaviour, I went with a module to make sure the caching is skipped.

File: test.js [hunk 3]
```diff
@@ -72,8 +73,16 @@ describe('v8flags', function () {
 
   it('should fall back to writing to a temp dir if user home can\'t be found', function (done) {
     eraseHome();
-    var v8flags = require('./');
-    var configfile = path.resolve(os.tmpdir(), v8flags.configfile);
+
+    delete require.cache[require.resolve('./config-path.js')];
```
Comment (Siilwyn) [inline test.js]: Sadly is required for `proxyquire` to work.

**Comment by phated** [comment]
@Siilwyn failing on appveyor.

**Comment by Siilwyn** [comment]
@phated think it's a false-negative, see: https://github.com/js-cli/js-v8flags/pull/43

**Comment by jonschlinkert** [comment]
> I can't get it to return null as it would need a Windows environment

is this a bug in `homedir-polyfill`? or is that the correct behavior for that lib?

cc @doowb

**Comment by Siilwyn** [comment]
@jonschlinkert it's correct behaviour I think. My wording was a bit bad: it can only return null in a Windows environment. But I solved it by mocking the behaviour so all's good. :)

**Comment by Siilwyn** [comment]
@phated since appveyor's failing is not caused by this PR can this be merged?

File: config-path.js [hunk 4]
```diff
@@ -21,6 +22,10 @@ function linux () {
 }
 
 module.exports = function (platform) {
+  if (!userHome) {
+    return os.tmpdir();
```
Comment (phated) [inline config-path.js]: How trustworthy is `os.tmpdir()` - I thought it could return null

File: package.json [hunk 5]
```diff
@@ -34,9 +34,11 @@
   "devDependencies": {
     "async": "^2.5.0",
     "chai": "^4.1.0",
-    "mocha": "^3.4.2"
+    "mocha": "^3.4.2",
+    "proxyquire": "^1.8.0",
+    "require-uncached": "^1.0.3"
```
Comment (phated) [inline package.json]: -1 on this devDep

File: test.js [hunk 6]
```diff
@@ -72,8 +73,16 @@ describe('v8flags', function () {
...
+    proxyquire('./config-path.js', {
```
Comment (phated) [inline test.js]: I don't like mocking dependency behavior.  I'd much rather you figure a real-world way to test this (appveyor is now activated properly).

File: test.js [hunk 7]
```diff
@@ -72,8 +73,16 @@ describe('v8flags', function () {
...
+      'homedir-polyfill': function () {
+        return null;
+      }
+    });
+
+    const v8flags = requireUncached('./');
```
Comment (phated) [inline test.js]: don't need this since we're already deleting from the require.cache, just delete 2 things

File: config-path.js (hunk 4 above)
Comment (Siilwyn) [inline config-path.js]: Os.tmpdir is already used in index, all I did is changed the location. Looks like it won't though: https://github.com/nodejs/node/blob/master/lib/os.js#L98

File: test.js (hunk 6 above)
Comment (Siilwyn) [inline test.js]: That would mean we only can test on Windows to which I don't have access.

**Comment by Siilwyn** [comment]
@phated ready for second review!

Moved the fallback directory test to config-path since that's where the logic went this also simplifies the mocking.

**Comment by phated** [comment]
@Siilwyn I need to get appveyor working before I sign off on this.  I'm trying to dig into it today.

**Comment by Siilwyn** [comment]
Okay! To be honest I don't think two CI providers are needed but it doesn't hurt either.
:thumbsup:

**Comment by phated** [comment]
@Siilwyn appveyor is a windows CI, which isn't provided by travis.  And you have something broken (from 3.0) in Windows.  We need to get it fixed.

**Comment by phated** [comment]
There seems to be a lot wrong with the 3.0 stuff and is taking me a lot of time to sort through.

**Comment by Siilwyn** [comment]
Thanks for checking it out phated! I've commented on your appveyor PR.

**Comment by Siilwyn** [comment]
So what's left to change? You mentioned:
- Needing to reset environment variables between tests, are `eraseHome` and `resetTemp` not covering all variables?
- Not liking the `proxyquire` dependency, I made better use of it by scoping it in f1f51d2. Without it the `homedir-polyfill` module needs to be forced down [the Windows path](https://github.com/doowb/homedir-polyfill/blob/master/index.js#L12) but tweaking `process.platform` only brought me pain in the past...

**Comment by phated** [comment]
@Siilwyn I'd like to see a test that's skipped on any non-windows platform (use `if (os.platform() !== 'win32')`) (ref https://nodejs.org/api/os.html#os_os_platform) that actually tests the scenario on the AppVeyor CI

**Comment by Siilwyn** [comment]
Personally dislike that because that means I can not test it locally but if you're sure about it I'll change it.

**Comment by phated** [comment]
@Siilwyn feel free to keep your mocked tests in to test locally, I just want a real-world scenario in the CI so it can catch anything we miss manually or in the mocks.

**Comment by Siilwyn** [comment]
@phated ah okay, misunderstanding from my part. Sounds good.

**Comment by Siilwyn** [comment]
@phated okay so the problem is I'm not sure if the native `os.homedir` ever returns anything else than a string. I tried to force it in several way, [the last result](https://ci.appveyor.com/project/phated/js-v8flags/build/59/job/nggmx742r4c2gjx0) using empty strings results in gibberish as the home directory. While deleting the variables [returns a 'null'](https://ci.appveyor.com/project/phated/js-v8flags/build/56/job/5aj9uucpuph8o53n) because the variable is set to a 'null'. So maybe the `homedir-polyfill` is wrong in the implementation returning `null` which means we don't even need a fallback...

**Comment by Siilwyn** [comment]
I mean I could make it working by only running the test on Windows if the Node version is <= 0.12, that way it tests if the polyfill returning null works...

**Comment by jonschlinkert** [comment]
> maybe the homedir-polyfill is wrong in the implementation returning null which means we don't even need a fallback...

is there a bug in homedir-polyfill? If so @doowb or I can fix it

**Comment by Siilwyn** [comment]
Hey @jonschlinkert thanks for tuning in. :) Didn't ping anybody of the polyfill project yet because I'm not sure but yes to me it looks like the native version never returns `null`.

**Comment by jonschlinkert** [comment]
> anybody of the polyfill

no worries, that project is maintained by @doowb and me

**Comment by Siilwyn** [comment]
Aha! @jonschlinkert so do you think the native homedir function ever returns `null`? Also tried to read the source code of Node.js but I can't quite follow.

**Comment by doowb** [comment]
> do you think the native homedir function ever returns null

From the tests that you linked to above, it looks like one of them is returning `null`. Since the tests are run on node 4 and node 6, `homedir-polyfill` just uses the `os.homedir` function since it's available.

The source code for getting the homedir is in `libuv` so it can be implemented using native OS bindings. In `homedir-polyfill` we tried to match the same functionality by going through the `libuv` implementation and making it as close to possible.

I think [this is the implementation](https://github.com/libuv/libuv/blob/d8cd08bd985b0d4f16f76c6c726b5b938b2ee9ee/src/win/util.c#L1144). At the bottom it does `return 0` when nothing is found. I think that might be similar to returning `null`, but it might not be. I'm happy to dig in more if anyone thinks that `homedir-polyfill` should return something other than `null` when the homedir cannot be determined.

**Comment by Siilwyn** [comment]
@doowb I see, thanks for the explanation! So there's this weird difference between the polyfill behaviour and the native implementation on [these CI tests](https://ci.appveyor.com/project/phated/js-v8flags/build/45). As you can see Node 0.10 & 0.12 don't find the home directory while the rest does, this is done by [this specific test](https://github.com/js-cli/js-v8flags/blob/db221c4f89e74d633e8dc2f3b226806635a5a045/test.js#L189-L202).

**Comment by Siilwyn** [comment]
Hi @doowb & @jonschlinkert don't want to be pushy, any idea on why the polyfill is behaving differently as described in my previous comment? I can't figure it out... hard to debug as it's OS and Node version specific.

**Comment by doowb** [comment]
I did some more digging and on windows `os.homedir` will fall back to using [this function](https://github.com/libuv/libuv/blob/d8cd08bd985b0d4f16f76c6c726b5b938b2ee9ee/src/win/util.c#L1377) if the `USERPROFILE` environment variable is not set. I don't know if there's a way to get that information from accessible files on Windows (that's how I do it on unix/macos).

I think this might be getting to a point where a note in the docs saying that node versions < 4.0 on windows will get config paths from the temp directory instead of the home directory due to limitations in node.

**Comment by Siilwyn** [comment]
@doowb yes a note will be fine, think I will just limit this test to node versions < 4.0. Regarding the official implementation, [this function(https://github.com/nodejs/node/blob/784c6d40f88c5a3b4270f2a6d4c7c120b4b12af6/src/node_os.cc#L317) seems to be wrapped around the libuv implementation and always return a string right?

**Comment by Siilwyn** [comment]
@phated merge this?

**Comment by doowb** [comment]
> always return a string right

Looks like there's a case there where it throws an error. I don't know how errors are handled in this case (from c to javascript). If we can figure it out, I'm more than happy to return the same value.

**Comment by Siilwyn** [comment]
@phated :ping_pong:

**Comment by phated** [comment]
Real life, I'll get back to you when I can

**Comment by phated** [comment]
@Siilwyn @doowb Just deleted the entire appveyor environment in https://ci.appveyor.com/project/phated/js-v8flags/build/94 and node >4 (when we aren't using the polyfill) is still able to find a directory.  Not sure what C or OS magic they use to get it but I suppose we'll be fine with this real-world test only being node <4.  I'll finish my review after dinner.

**Comment by phated** [comment]
Published as 3.0.1 since it was fixing a couple bugs.
